apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-devops-demo
  labels:
    app: react-devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-devops-demo
  template:
    metadata:
      labels:
        app: react-devops-demo
    spec:
      containers:
        - name: react-devops-demo
          image: localhost:5000/react-devops-demo:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: react-devops-demo
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30390
      protocol: TCP
      targetPort: 3000
  selector:
    app: react-devops-demo