# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy React Application

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Setup User Information
      run: |
        git config --global user.email "yusungkung35@gmail.com"
        git config --global user.name "cloudyk123"
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn run build --if-present
    - run: yarn test
    - name: Git clone gh-pages
      run: git clone git@github.com:cloudyk123/react-containerization.git -b gh-pages
    - name: deploy to gh-pages
      run: yarn run deploy
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#         publish_dir: ./build
